//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amarok.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amarok.Contracts.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty collection is not valid..
        /// </summary>
        internal static string ArgumentEmptyCollection {
            get {
                return ResourceManager.GetString("ArgumentEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty string is not valid..
        /// </summary>
        internal static string ArgumentEmptyString {
            get {
                return ResourceManager.GetString("ArgumentEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value exceeding the upper limit is not valid..
        /// </summary>
        internal static string ArgumentIsLessThan {
            get {
                return ResourceManager.GetString("ArgumentIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative value is not valid..
        /// </summary>
        internal static string ArgumentIsPositive {
            get {
                return ResourceManager.GetString("ArgumentIsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value exceeding the upper limit is not valid..
        /// </summary>
        internal static string ArgumentIsStrictlyLessThan {
            get {
                return ResourceManager.GetString("ArgumentIsStrictlyLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or a negative value are not valid..
        /// </summary>
        internal static string ArgumentIsStrictlyPositive {
            get {
                return ResourceManager.GetString("ArgumentIsStrictlyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null value is not valid..
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper limit: .
        /// </summary>
        internal static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
    }
}
