name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    steps:

    # Prepare
      
      - name: Install .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x        

      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x        
      
      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x        

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install Stryker
        run: dotnet tool install --global dotnet-stryker

      - name: Get sources
        uses: actions/checkout@v2

      - name: Restore packages
        run: dotnet restore


    # Build and Test (Debug) with Sonar Scanner

      - name: Prepare SonarScanner
        run: dotnet sonarscanner begin /k:"Amarok79_Contracts" /o:"amarok79-github" /v:"1.0.0" /d:sonar.host.url="https://sonarcloud.io"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Debug
        run: dotnet build --configuration Debug

      - name: Run tests
        run: dotnet test --no-build --collect "Code Coverage"
      
      - name: Finish SonarScanner
        run: dotnet sonarscanner end
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


    # Run Mutation Tests

      - name: Clean up
        run: git clean -d -x -f

      - name: Run mutation tests
        run: dotnet stryker

      - name: Upload Stryker Output
        uses: actions/upload-artifact@v2
        with:
          name: mutation-tests
          path: '**/mutation-report.html'
          if-no-files-found: error


    # Build and Publish (Release)

      - name: Clean up
        run: git clean -d -x -f

      - name: Build Release
        run: dotnet build --configuration Release

      - name: Build NuGet package
        run: _pack.cmd
        shell: cmd

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: bin/lib/*.nupkg
          if-no-files-found: error
