name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    steps:

    # Prepare
      
      - name: Install .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x        

      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x        
      
      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x        

      - name: Get sources
        uses: actions/checkout@v2

      - name: Restore packages
        run: dotnet restore


    # Build and Test (Debug)

      - name: Build Debug
        run: dotnet build --configuration Debug

      - name: Run tests
        run: dotnet test --no-build


    # Build and Publish (Release)

      - name: Clean up
        run: git clean -d -x -f

      - name: Build Release
        run: dotnet build --configuration Release

      - name: Build NuGet package
        run: _pack.cmd
        shell: cmd

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: bin/lib/*.nupkg
          if-no-files-found: error
