name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Prepare

      - name: Install .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x

      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install Java 13.0.x
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.x
          java-package: jdk

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install Stryker
        run: dotnet tool install --global dotnet-stryker

      - name: Get sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Build and Test (Debug) with Sonar Scanner

      - name: Restore packages
        run: dotnet restore

      - name: Prepare SonarScanner
        run: dotnet sonarscanner begin /k:"Amarok.Contracts" /o:"amarok79-github" /v:"1.0.0" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Debug
        run: dotnet build --configuration Debug

      - name: Run tests
        run: dotnet test --no-build --collect "Code Coverage"

      - name: Finish SonarScanner
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Shut down build server
        run: dotnet build-server shutdown

      - name: Clean up
        run: git clean -d -x -f

      # Run Mutation Tests

      - name: Restore packages
        run: dotnet restore

      - name: Run mutation tests
        run: dotnet stryker

      - name: Upload Stryker Output
        uses: actions/upload-artifact@v2
        with:
          name: mutation-tests
          path: "**/mutation-report.html"
          if-no-files-found: error

      - name: Shut down build server
        run: dotnet build-server shutdown

      - name: Clean up
        run: git clean -d -x -f

      # Build and Publish (Release)

      - name: Restore packages
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release

      - name: Build NuGet package
        run: _pack.cmd
        shell: cmd

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: bin/lib/*.nupkg
          if-no-files-found: error
